# 注解源码
```java
// 可以用在类上，也可以用在方法上
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Documented
public @interface Transactional {
    // value 和 transactionManager 等价，指定事务管理器
    @AliasFor("transactionManager")
    String value() default "";

    @AliasFor("value")
    String transactionManager() default "";

    //事务传播机制，默认是 REQUIRED
    Propagation propagation() default Propagation.REQUIRED;

    //事务隔离级别，默认使用数据库的隔离级别
    Isolation isolation() default Isolation.DEFAULT;

    int timeout() default -1;

    boolean readOnly() default false;

    // 指定回滚的异常类 Class 对象
    Class<? extends Throwable>[] rollbackFor() default {};

    // 指定回滚的异常类名
    String[] rollbackForClassName() default {};

    // 指定不回滚的异常类 Class 对象
    Class<? extends Throwable>[] noRollbackFor() default {};

    // 指定不回滚的异常类名
    String[] noRollbackForClassName() default {};
}
```
___
# 事务隔离级别
默认的隔离级别是与数据库保持一致
如果指定了其他隔离级别， JDBC 从数据库获取一个连接 Connection 对象时，尝试将此连接对象的事务隔离级别更改为给定的级别

# 事务传播机制
## PROPAGATION_REQUIRED
默认选项
如果当前没有事务，就新建一个事务，如果已经存在一个事务中，加入到这个事务中。这是最常见的选择。

## PROPAGATION_SUPPORTS
支持当前事务，如果当前没有事务，就以非事务方式执行。

## PROPAGATION_MANDATORY
使用当前的事务，如果当前没有事务，就抛出异常。

## PROPAGATION_REQUIRES_NEW
新建事务，如果当前存在事务，把当前事务挂起。

## PROPAGATION_NOT_SUPPORTED
以非事务方式执行操作，如果当前存在事务，就把当前事务挂起。

## PROPAGATION_NEVER
以非事务方式执行，如果当前存在事务，则抛出异常。

## PROPAGATION_NESTED
如果当前存在事务，则在嵌套事务内执行。如果当前没有事务，则执行与PROPAGATION_REQUIRED类似的操作。

## 区分 REQUIRED REQUIRES_NEW NESTED
假设 methodA 中调用 methodB

### REQUIRED
A 和 B 处于同一个事务中，A 和 B 同提交同回滚，只有 AB 都没有异常才会 commit
此时如果 B 抛出异常， A 也要抛出才行，不要捕获但不抛出，否则会报错
B 抛出异常的时候，spring 事务会标记 global rollback-only
此时后面事务如果有 commit 操作，会在`org.springframework.transaction.support.AbstractPlatformTransactionManager#processCommit`方法中
```java
	private void processCommit(DefaultTransactionStatus status) throws TransactionException {
        ...
        // Throw UnexpectedRollbackException if we have a global rollback-only
        // marker but still didn't get a corresponding exception from commit.
        if (unexpectedRollback) {
            throw new UnexpectedRollbackException(
                    "Transaction silently rolled back because it has been marked as rollback-only");
        }
        ...
    }
```
此时会抛出 UnexpectedRollbackException 异常

### REQUIRES_NEW
A 和 B 属于两个事务了，互相不影响提交回滚，此时也就是 A 与 B 的提交回滚是有顺序的，一定是 B 事务先提交或回滚，再到 A。
因为是 A 中调用 B ，如果 B 抛出异常则 B 回滚，此时 A 可以通过选择捕获这个异常抛出或者不抛出，来决定自己是否回滚。

### NESTED
B 是 A 的子事务，B 只能和 A 一起提交
如果 A 回滚，B 一定会跟着回滚
但是如果 B 回滚，A 可以选择回滚，也可以选择正常提交
___
# 事务失效场景
## 1. this 调用
当我们在 service 中有事务方法 methodA 和事务方法 methodB 的时候，如果 A 内要调用 B，使用 this.methodB() 的话，方法 B 内的操作会没有事务处理。
因为事务的增强是由代理得到的， this 获取的是原生的 service 对象，没有经过代理，也就没有事务了
### 解决
1. 获取当前的代理对象来调用 methodB
在当前类上添加注解
```java
@EnableAspectJAutoProxy(exposeProxy = true)
```
然后就可以用下面的代码得到当前类的代理类
```java
    XXXService service = (XXXTabService) AopContext.currentProxy();
    service.methodB();
``` 
2. 从 Spring 容器中获取 Bean
先注入 ApplicationContext
```java
    @Autowired
    private ApplicationContext ctx;
```
再通过`ApplicationContext`获取当前 service 的 bean ，得到的就是容器中已经经过 AOP 代理产生的实例对象，再调用 methodB
```java
    XXXService service = ctx.getBean(XXXService.class);
    service.methodB();
```

## 2. 非 public 方法
事务的增强是由代理得到的，`@Transactional`在生成代理时会判断，如果方法为非 public 修饰的方法，则不生成代理对象，这样也就没办法自动回滚事务了

## 3. 没有抛出异常
异常被捕获后没有重新抛出，没有抛出异常就不会自动回滚
### 解决
1. 抛出异常
2. 手动回滚
```java
    try {
        ...
    } catch (Throwable e) {
        ...
        TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
        ...
    }
```

## 4. 异常类型错误
@Transactional 默认只回滚运行时异常 RuntimeException 和 Error，而对于检查异常默认是不回滚的
在事务调用链中`org.springframework.transaction.interceptor.TransactionAspectSupport#invokeWithinTransaction`
```java
	@Nullable
	protected Object invokeWithinTransaction(Method method, @Nullable Class<?> targetClass,
			final InvocationCallback invocation) throws Throwable {
                ...
                if (txAttr == null || !(ptm instanceof CallbackPreferringPlatformTransactionManager)) {
                    ...
                    Object retVal;
                    try {
                        // This is an around advice: Invoke the next interceptor in the chain.
                        // This will normally result in a target object being invoked.
                        retVal = invocation.proceedWithInvocation();
                    }
                    catch (Throwable ex) {
                        // target invocation exception
                        completeTransactionAfterThrowing(txInfo, ex);
                        throw ex;
                    }
                    ...
                }
                ...
            }
```
在调用`proceedWithInvocation()`内执行了目标方法后，如果抛出异常，则进入到`org.springframework.transaction.interceptor.TransactionAspectSupport#completeTransactionAfterThrowing`
```java
	protected void completeTransactionAfterThrowing(@Nullable TransactionInfo txInfo, Throwable ex) {
		if (txInfo != null && txInfo.getTransactionStatus() != null) {
            ...
            // txInfo.transactionAttribute.rollbackOn(ex) 就是判断这个 ex 是否要回滚的地方
			if (txInfo.transactionAttribute != null && txInfo.transactionAttribute.rollbackOn(ex)) {
				try {
					txInfo.getTransactionManager().rollback(txInfo.getTransactionStatus());
				}
				catch (TransactionSystemException ex2) {
					logger.error("Application exception overridden by rollback exception", ex);
					ex2.initApplicationException(ex);
					throw ex2;
				}
				catch (RuntimeException | Error ex2) {
					logger.error("Application exception overridden by rollback exception", ex);
					throw ex2;
				}
			}
			...
		}
	}
```
`txInfo.transactionAttribute.rollbackOn(ex)`默认会调用到`org.springframework.transaction.interceptor.DefaultTransactionAttribute`中
```java
	/**
	 * The default behavior is as with EJB: rollback on unchecked exception
	 * ({@link RuntimeException}), assuming an unexpected outcome outside any
	 * business rules. Additionally, we also attempt to rollback on {@link Error} which
	 * is clearly an unexpected outcome as well. By contrast, a checked exception is
	 * considered a business exception and therefore a regular expected outcome of the
	 * transactional business method, i.e. a kind of alternative return value which
	 * still allows for regular completion of resource operations.
	 * <p>This is largely consistent with TransactionTemplate's default behavior,
	 * except that TransactionTemplate also rolls back on undeclared checked exceptions
	 * (a corner case). For declarative transactions, we expect checked exceptions to be
	 * intentionally declared as business exceptions, leading to a commit by default.
	 * @see org.springframework.transaction.support.TransactionTemplate#execute
	 */
	@Override
	public boolean rollbackOn(Throwable ex) {
		return (ex instanceof RuntimeException || ex instanceof Error);
	}
```
可见默认情况下只会处理 RuntimeException 和 Error
### 解决
此问题的解决方案是给 @Transactional 注解上，添加 rollbackFor 参数并设置 Exception.class 值






